### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by chocolate42** [chocolate42/flaccid#4]
- [x] flac-test-files fails on track 45, because sample count is not present in the header. This should be rare in the wild. Issue with flac loader which will probably fix itself when input gets overhauled
- [x] Fixed mode can't use finalising boilerplate because partial end frame has to be done manually
- [ ] getopt is a mess
- [x] When input is flac and we are hashing, check that input MD5 matches output MD5
- [x] Potential way to simplify gset with _eof function
- [x] Implement seektable when output is seekable. Seekpoint every few seconds when total_samples is known in advance? Otherwise use a fixed number of seekpoints and try to evenly space them? Maybe forget the first option and just let user choose seekpoint count with a default of 50 and do the latter.
- [x] #7
- [ ] A smarter tweak pass could read how the frames being tweaked encoded their input to decide if it's worth testing a tweak of these frames (currently it's brute force). Maybe there's a correlation between model similarity and tweakability that can be used to discard unlikely candidates before we test them
- [ ] Same goes for merge, maybe similar models makes it more likely that a merge would be beneficial
- [ ] Maybe when tweak does a test encode (with or without being smart), narrower flac settings can be used that better match what the prior encodes did (for example if both frames could have used -l6 but the LPC order chosen was 3, the test encodes could potentially be done with -l3)
- [ ] Likewise a smarter merge pass could do the same
- [x] #8

Don't want to mess about with metadata much so it's unlikely preserving metadata from any other source will be implemented as that would be painful.
